services:
  reverse-proxy:
    image: traefik:v3.3
    restart: unless-stopped
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TRAEFIK_HTTP_PORT:80"
      - "$TRAEFIK_HTTPS_PORT:443"
      - "$GATEWAY_PORT:8080"
    volumes:
      - ./certs:/certs:ro
      - ./conf/traefik:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
