services:
  reverse-proxy:
    image: traefik:v3.3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TRAEFIK_HTTP_PORT:80"
      - "$TRAEFIK_HTTPS_PORT:443"
      - "$GATEWAY_PORT:8080"
    volumes:
      - /home/raftkon/projects/express-auth/system/certs:/certs:ro
      - /home/raftkon/projects/express-auth/system/conf/traefik:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
